;; -*- coding: utf-8-emacs; -*-
(setq nnrss-group-data '((14 (26641 54080 728316 589000) "https://www.linuxtrent.it/non-cambiare-pc-passa-a-linux-invece/" "Non cambiare PC, passa a Linux invece" "Daniele Piccoli" "Tue, 29 Apr 2025 03:59:17 +0000" "<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2025/04/Non_cambiare_pc_passa_a_Linux.png\"><img fetchpriority=\"high\" decoding=\"async\" class=\"size-medium wp-image-8929 alignleft\" src=\"https://www.linuxtrent.it/wp-content/uploads/2025/04/Non_cambiare_pc_passa_a_Linux-212x300.png\" alt=\"Non cambiare pc, passa a linux - serata 13 maggio 2025\" width=\"212\" height=\"300\" srcset=\"https://www.linuxtrent.it/wp-content/uploads/2025/04/Non_cambiare_pc_passa_a_Linux-212x300.png 212w, https://www.linuxtrent.it/wp-content/uploads/2025/04/Non_cambiare_pc_passa_a_Linux-724x1024.png 724w, https://www.linuxtrent.it/wp-content/uploads/2025/04/Non_cambiare_pc_passa_a_Linux-768x1086.png 768w, https://www.linuxtrent.it/wp-content/uploads/2025/04/Non_cambiare_pc_passa_a_Linux.png 794w\" sizes=\"(max-width: 212px) 100vw, 212px\" /></a>Serata a tema che si terrà <strong>martedì 13 maggio 2025, dalle ore 18.00 alle ore 19.30</strong>, presso lo <a href=\"https://www.openstreetmap.org/relation/1919517\" target=\"_blank\" rel=\"noopener\">Sportello Linux di Rovereto</a></p>
<p>Parleremo di sistemi operativi basati su Linux e pronti all’uso per dare nuova linfa ai nostri computer che potrebbero non supportare il nuovo Windows 11. Negli ultimi anni, le caratteristiche hardware di quasi tutti i computer sul commercio permetto un utilizzo fluido e un esperienza piacevole usando una delle tante distribuzioni Linux disponibili. Quello che risulta difficile è fare la scelta giusta.</p>
<p>Durante il corso della serata vi presenteremo quelle che per noi sono le scelte migliori su cui puntare e quindi vedremo come installare il sistema scelto sul nostro computer affrontando le casistiche che di volta in volta possono nascere</p>
<p>Una volta poi avviato il computer con il nuovo sistema operativo, scopriremo assieme quali sono i software di utilizzo comune che possiamo usare per soddisfare le nostre esigenze</p>
<p>Vi aspettiamo numerosi</p>
" nil nil "9187f04fb0a2f0d9b8c4d59e6d2608b8") (13 (26641 54080 727378 703000) "https://www.linuxtrent.it/linuxday-2024/" "LinuxDay 2024" "Daniele Piccoli" "Sat, 26 Oct 2024 12:41:05 +0000" "<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2019/10/linuxday_fullcolor-e1571653106187.png\"><img decoding=\"async\" class=\"size-medium wp-image-1122 alignleft\" src=\"https://www.linuxtrent.it/wp-content/uploads/2019/10/linuxday_fullcolor-297x300.png\" alt=\"\" width=\"297\" height=\"300\" /></a>Questo pomeriggio durante l’edizione LinuxDay di Bolzano, ci sarà un intervento su XMPP in collaborazione con LinuxTrent e la comunità italiana (<a href=\"https://www.xmpp-it.net/\" target=\"_blank\" rel=\"noopener\">https://www.xmpp-it.net/</a>)</p>
<p><strong>Inizio alle ore 15.00</strong></p>
<p>Sarà possibile seguire la diretta streaming a questo indirizzo:  <a href=\"https://video.xmpp-it.net/c/happyhour\" target=\"_blank\" rel=\"noopener\">https://video.xmpp-it.net/c/happyhour</a></p>
<p>Info evento Bolzano disponibili al link: <a href=\"https://lugbz.org/linuxday2024/\" target=\"_blank\" rel=\"noopener\">https://lugbz.org/linuxday2024/</a></p>
" nil nil "b30780e3803ff858294a22f987dd0b02") (12 (26630 29042 919597 707000) "https://www.linuxtrent.it/primi-passi-nel-mondo-iot-con-arduino/" "Primi passi nel mondo IOT con Arduino" "Daniele Piccoli" "Wed, 26 Mar 2025 15:15:14 +0000" "<h3 style=\"text-align: left;\"><a href=\"https://www.linuxtrent.it/wp-content/uploads/2025/03/arduino_8_04_2025.pdf\"><strong><span style=\"color: #ff0000;\">Scarica le slide della serata</span></strong></a></h3>
<hr />
<p><strong>Martedì 8 aprile 2025</strong> riapre lo sportello Linux di Rovereto con il 1° appuntamento dove parleremo di IoT con Arduino. Scopriremo quali sono le schede disponibili e i relativi componenti abbinabili per poi passare a scoprire l’ambiente di sviluppo. Finiremo con il mostrarvi alcuni esempi di utilizzo concreto.</p>
<p><b>Arduino</b> è una <a title=\"Piattaforma (informatica)\" href=\"https://it.wikipedia.org/wiki/Piattaforma_(informatica)\">piattaforma hardware e software</a> composta da una serie di <a title=\"Scheda elettronica\" href=\"https://it.wikipedia.org/wiki/Scheda_elettronica\">schede elettroniche</a> dotate di un <a title=\"Microcontrollore\" href=\"https://it.wikipedia.org/wiki/Microcontrollore\">microcontrollore</a> e software a corredo che ne permette la programmazione in modalità semplificata.</p>
<p>Con Arduino si possono realizzare in maniera relativamente rapida e semplice piccoli <a title=\"Dispositivo (informatica)\" href=\"https://it.wikipedia.org/wiki/Dispositivo_(informatica)\">dispositivi</a> come controllori di luci, di velocità per motori, sensori di luce, automatismi per il controllo della temperatura e dell’umidità e molti altri progetti che utilizzano <a class=\"mw-redirect\" title=\"Sensori\" href=\"https://it.wikipedia.org/wiki/Sensori\">sensori</a>, <a class=\"mw-redirect\" title=\"Attuatori\" href=\"https://it.wikipedia.org/wiki/Attuatori\">attuatori</a> e comunicazione con altri dispositivi. La scheda è abbinata a un semplice <a title=\"Ambiente di sviluppo integrato\" href=\"https://it.wikipedia.org/wiki/Ambiente_di_sviluppo_integrato\">ambiente di sviluppo integrato</a> per la <a title=\"Programmazione (informatica)\" href=\"https://it.wikipedia.org/wiki/Programmazione_(informatica)\">programmazione</a> del microcontrollore. Tutto il <a title=\"Software\" href=\"https://it.wikipedia.org/wiki/Software\">software</a> a corredo è <a title=\"Software libero\" href=\"https://it.wikipedia.org/wiki/Software_libero\">libero</a>, e gli schemi circuitali sono distribuiti come <a title=\"Hardware libero\" href=\"https://it.wikipedia.org/wiki/Hardware_libero\">hardware libero</a> e per questo motivo è molto utilizzato nella didattica educativa<sup id=\"cite_ref-3\" class=\"reference\"><a href=\"https://it.wikipedia.org/wiki/Arduino_(hardware)#cite_note-3\"><span class=\"cite-bracket\">[</span>3<span class=\"cite-bracket\">]</span></a></sup>.</p>
<p>Fonte: <a href=\"https://it.wikipedia.org/wiki/Arduino_(hardware)\">https://it.wikipedia.org/wiki/Arduino_(hardware)</a></p>
" nil nil "6154375239f809130c709c43716dffd7") (11 (26596 20179 285642 239000) "https://www.linuxtrent.it/primi-passi-nel-mondo-iot-con-arduino/" "Primi passi nel mondo IOT con Arduino" "Daniele Piccoli" "Wed, 26 Mar 2025 15:15:14 +0000" "<p><strong>Martedì 8 aprile 2025</strong> riapre lo sportello Linux di Rovereto con il 1° appuntamento dove parleremo di IoT con Arduino. Scopriremo quali sono le schede disponibili e i relativi componenti abbinabili per poi passare a scoprire l’ambiente di sviluppo. Finiremo con il mostrarvi alcuni esempi di utilizzo concreto.</p>
<p><b>Arduino</b> è una <a title=\"Piattaforma (informatica)\" href=\"https://it.wikipedia.org/wiki/Piattaforma_(informatica)\">piattaforma hardware e software</a> composta da una serie di <a title=\"Scheda elettronica\" href=\"https://it.wikipedia.org/wiki/Scheda_elettronica\">schede elettroniche</a> dotate di un <a title=\"Microcontrollore\" href=\"https://it.wikipedia.org/wiki/Microcontrollore\">microcontrollore</a> e software a corredo che ne permette la programmazione in modalità semplificata.</p>
<p>Con Arduino si possono realizzare in maniera relativamente rapida e semplice piccoli <a title=\"Dispositivo (informatica)\" href=\"https://it.wikipedia.org/wiki/Dispositivo_(informatica)\">dispositivi</a> come controllori di luci, di velocità per motori, sensori di luce, automatismi per il controllo della temperatura e dell’umidità e molti altri progetti che utilizzano <a class=\"mw-redirect\" title=\"Sensori\" href=\"https://it.wikipedia.org/wiki/Sensori\">sensori</a>, <a class=\"mw-redirect\" title=\"Attuatori\" href=\"https://it.wikipedia.org/wiki/Attuatori\">attuatori</a> e comunicazione con altri dispositivi. La scheda è abbinata a un semplice <a title=\"Ambiente di sviluppo integrato\" href=\"https://it.wikipedia.org/wiki/Ambiente_di_sviluppo_integrato\">ambiente di sviluppo integrato</a> per la <a title=\"Programmazione (informatica)\" href=\"https://it.wikipedia.org/wiki/Programmazione_(informatica)\">programmazione</a> del microcontrollore. Tutto il <a title=\"Software\" href=\"https://it.wikipedia.org/wiki/Software\">software</a> a corredo è <a title=\"Software libero\" href=\"https://it.wikipedia.org/wiki/Software_libero\">libero</a>, e gli schemi circuitali sono distribuiti come <a title=\"Hardware libero\" href=\"https://it.wikipedia.org/wiki/Hardware_libero\">hardware libero</a> e per questo motivo è molto utilizzato nella didattica educativa<sup id=\"cite_ref-3\" class=\"reference\"><a href=\"https://it.wikipedia.org/wiki/Arduino_(hardware)#cite_note-3\"><span class=\"cite-bracket\">[</span>3<span class=\"cite-bracket\">]</span></a></sup>.</p>
<p>Fonte: <a href=\"https://it.wikipedia.org/wiki/Arduino_(hardware)\">https://it.wikipedia.org/wiki/Arduino_(hardware)</a></p>
" nil nil "63f5d529d84062265a25cb7848feb872") (10 (26589 17394 708138 229000) "https://www.linuxtrent.it/senza-via-di-scampo/" "Senza via di scampo" "Roberto Resoli" "Mon, 16 Dec 2024 13:09:01 +0000" "<p>Sull’onda del buon riscontro avuto per il <a href=\"https://www.linuxtrent.it/io-e-i-miei-dati/\" target=\"_blank\" rel=\"noopener\">precedente incontro</a>, <strong>giovedì 19 Dicembre  2024 alle 20:30</strong> a <strong>Sover</strong> <strong>Diaolin</strong> e <strong>Roberto</strong> continuano il dialogo con chi vorrà partecipare.</p>
<p>Anche questa volta c’è stata una <strong>diretta</strong> <strong>sul nostro server Peertube</strong>, nel <a href=\"https://video.linuxtrent.it/c/incontri\" target=\"_blank\" rel=\"noopener\">canale ‘Incontri’</a>, con una <strong>chat contestuale</strong> per intervenire direttamente. La registrazione della serata è ora disponibile sullo stesso canale; nella <a href=\"http://www.linuxtrent.it/senza-via-di-scampo-materiali-e-riferimenti\" target=\"_blank\" rel=\"noopener\">pagina dedicata</a> saranno man mano pubblicati materiale e riferimenti relativi agli argomenti trattati.</p>
" nil nil "1792bfb52b2529540623358f9ebb67ed") (9 (26589 17394 708006 206000) "https://www.linuxtrent.it/io-e-i-miei-dati/" "Io e i miei dati!" "Roberto Resoli" "Fri, 29 Nov 2024 07:53:58 +0000" "<p>Il <strong>29 Novembre 2024</strong> alle <strong>20:30</strong> a <strong>Sover</strong> <strong>Diaolin</strong> e <strong>Roberto</strong> dialogheranno con chi c’è sul tema delle informazioni sulle nostre vite, su come vengono gestite e trasmesse, e sugli effetti per ognuno di noi.</p>
<p><strong>A stasera!</strong></p>
<p>Aggiornamento:</p>
<p>La <strong>registrazione</strong> é disponibile sul nostro server Peertube (nel canale “Incontri”: <a href=\"https://video.linuxtrent.it/c/incontri\" target=\"_blank\" rel=\"noopener\">https://video.linuxtrent.it/c/incontri</a>).</p>
<p><strong> </strong></p>
" nil nil "a9a2c3a5c6915878327362d6ad22e2bb") (8 (26589 17394 707887 161000) "https://www.linuxtrent.it/linuxday-2024/" "LinuxDay 2024" "Daniele Piccoli" "Sat, 26 Oct 2024 12:41:05 +0000" "<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2019/10/linuxday_fullcolor-e1571653106187.png\"><img fetchpriority=\"high\" decoding=\"async\" class=\"size-medium wp-image-1122 alignleft\" src=\"https://www.linuxtrent.it/wp-content/uploads/2019/10/linuxday_fullcolor-297x300.png\" alt=\"\" width=\"297\" height=\"300\" /></a>Questo pomeriggio durante l’edizione LinuxDay di Bolzano, ci sarà un intervento su XMPP in collaborazione con LinuxTrent e la comunità italiana (<a href=\"https://www.xmpp-it.net/\" target=\"_blank\" rel=\"noopener\">https://www.xmpp-it.net/</a>)</p>
<p><strong>Inizio alle ore 15.00</strong></p>
<p>Sarà possibile seguire la diretta streaming a questo indirizzo:  <a href=\"https://video.xmpp-it.net/c/happyhour\" target=\"_blank\" rel=\"noopener\">https://video.xmpp-it.net/c/happyhour</a></p>
<p>Info evento Bolzano disponibili al link: <a href=\"https://lugbz.org/linuxday2024/\" target=\"_blank\" rel=\"noopener\">https://lugbz.org/linuxday2024/</a></p>
" nil nil "c449415af17a6ac7a2095d5b8ce714d0") (7 (26589 17394 707735 121000) "https://www.linuxtrent.it/usare-nextcloud-per-collaborare-in-riservatezza/" "Nextcloud: collaborare in una Associazione, in piena riservatezza." "Roberto Resoli" "Fri, 14 Jun 2024 10:30:10 +0000" "<p><strong>Aggiornamento</strong>: <a href=\"https://video.linuxtrent.it/c/incontri/videos\" target=\"_blank\" rel=\"noopener\">Video sul canale “incontri”</a> dell’istanza PeerTube di LinuxTrent!</p>
<p><strong>LinuxTrent</strong> utilizza da anni <a href=\"https://nextcloud.com\" target=\"_blank\" rel=\"noopener\"><strong>Nextcloud</strong></a> per gestire la <strong>collaborazione</strong> tra soci e non, e per la <strong>gestione ordinaria dell’Associazione</strong>. Abbiamo deciso di <strong>illustrare pubblicamente</strong> questo potente strumento, a vantaggio sia di altre <strong>associazioni</strong> che di single <strong>persone</strong> che abbiano a cuore la propria riservatezza.</p>
<p>Nextcloud permette di sostituire praticamente tutti gli strumenti <strong>cosiddetti</strong> “gratuiti” disponibili in rete, che in realtà vengono pagati con i propri (meta)dati e la propria attenzione.</p>
<p>L’incontro si svolgerà <strong>Martedì 18 Giugno</strong> dalle <strong>18:00 alle 20:00</strong> presso gli <a href=\"https://www.esperanto.trento.it/lassociazione/dovesiamo/\" target=\"_blank\" rel=\"noopener\">spazi dell’Associazione Esperantista Trentina in via Zara 7/A</a>.</p>
<p>Dato che gli spazi sono limitati, <strong>vi chiediamo di annunciare la vostra presenza</strong>, utilizzando l’<a href=\"https://mobilizon.it/events/19f58a01-b81b-4be0-b629-f1f4268dbb0e\" target=\"_blank\" rel=\"noopener\">evento predisposto sulla piattaforma Mobilizon.it</a>. (Mobilizon non vi traccia e rispetta la vostra riservatezza).</p>
<p><strong>Vi aspettiamo!</strong></p>
<p> </p>
" nil nil "5b56bda97f126a13699de325d7520241") (6 (26589 17394 707224 24000) "https://www.linuxtrent.it/inaugurazione-collaborazione-linuxtrent-associazione-esperantista-trentina/" "Inaugurazione collaborazione LinuxTrent =?utf-8?Q?=E2=80=93?= Associazione Esperantista Trentina" "Marco Ciampa" "Wed, 24 Jan 2024 00:28:24 +0000" "<p><strong>Venerdì 26 gennaio 2024</strong>, dalle ore 17, presso la <a href=\"https://www.esperanto.trento.it/lassociazione/dovesiamo/\">sede dell’Associazione Esperantista Trentina</a>, a Trento in via Zara 7/A,<br />
avrà luogo un rinfresco assieme alle due associazioni di promozione sociale,<br />
LinuxTrent e Associazione Esperantista Trentina (AET),<br />
per festeggiare l’inizio della collaborazione<br />
con l’iniziativa “Sportello Linux” che si svolgerà,<br />
a partire martedì 30 gennaio, presso la sede dell’AET.</p>
<p><strong>Siete tutti invitati e con preghiera di diffusione.</strong></p>
" nil nil "001babb33f668a2dcbec5a6d2e7f3206") (5 (26589 17394 706741 805000) "https://www.linuxtrent.it/software-libero-e-consapevolezza-digitale-introduzione-stagione-23-24/" "Software libero e consapevolezza digitale =?utf-8?Q?=E2=80=93?= introduzione stagione 23/24" "Daniele Piccoli" "Tue, 19 Sep 2023 20:12:46 +0000" "<p><strong><a href=\"https://www.linuxtrent.it/wp-content/uploads/2023/09/resized_daniele-piccoli-20-set-23.png\"><img decoding=\"async\" class=\"size-medium wp-image-8639 alignleft\" src=\"https://www.linuxtrent.it/wp-content/uploads/2023/09/resized_daniele-piccoli-20-set-23-212x300.png\" alt=\"Locandina introduzione software libero presso biblioteca di Ala\" width=\"212\" height=\"300\" srcset=\"https://www.linuxtrent.it/wp-content/uploads/2023/09/resized_daniele-piccoli-20-set-23-212x300.png 212w, https://www.linuxtrent.it/wp-content/uploads/2023/09/resized_daniele-piccoli-20-set-23.png 724w\" sizes=\"(max-width: 212px) 100vw, 212px\" /></a>Mercoledì 20 settembre 2023</strong>, alle ore 16.30, in occasione della ripresa dello sportello Linux presso la <a href=\"https://www.openstreetmap.org/node/2517370249\" target=\"_blank\" rel=\"noopener\">biblioteca di Ala</a>, ci sarà una breve presentazione per introdurre il software libero e il mondo che lo circonda.</p>
<p>Inoltre affronteremo il problema della sorveglianza digitale durante l’uso della rete e dei problemi di privacy che ne conseguono, cercando anche di illustrare le possibili soluzioni per mitigare il problema.</p>
<p>INGRESSO GRATUITO</p>
" nil nil "3248a8c383e5e8cfd0bcadba15c44dcd") (4 (26589 17394 706582 120000) "https://www.linuxtrent.it/iniziare-ad-usare-xmpp-e-snikket/" "Iniziare ad usare XMPP e Snikket" "Roberto Resoli" "Thu, 20 Jul 2023 07:43:38 +0000" "<p>(Aggiornamento: <strong><a href=\"https://video.linuxtrent.it/w/cTK2T4843753oHpb7s4wVn\" target=\"_blank\" rel=\"noopener\">video</a></strong> della serata, con <strong>chat associata per domande e risposte</strong>, puoi anche <a href=\"xmpp:604dfa29-c1db-4f3d-95f9-f8202a4d3727@room.video.linuxtrent.it?join\">entrare direttamente in chat con un client xmpp</a>)</p>
<p>(Aggiornamento: <strong><a href=\"https://peertube.debian.social/w/jVMWVYSUdT4Jz5WBJvaZUS\" target=\"_blank\" rel=\"noopener\">video catturato da Dashamir</a>, con una migliore regia</strong>)</p>
<p>Il <strong><a href=\"https://www.lugbz.org/\" target=\"_blank\" rel=\"noopener\">Linux User Group di Bolzano</a></strong> e il <strong><a href=\"https://fuss.bz.it/post/2023-07-20_xmpp/\" target=\"_blank\" rel=\"noopener\">progetto FUSS</a></strong>, in collaborazione con <strong>LinuxTrent</strong>, organizzano un <a href=\"https://www.lugbz.org/events/workshop-xmpp-snikket/\" target=\"_blank\" rel=\"noopener\">laboratorio pratico</a> introduttivo alla <strong>messaggistica decentrata XMPP</strong>. L’evento si svolgerà il <strong>20 Luglio 2023 alle 18:00</strong> a <strong><a href=\"https://osm.org/go/0IQB95oyj?way=164499375\" target=\"_blank\" rel=\"noopener\">Bolzano presso l’Intendenza scolastica  in lingua italiana di via del Ronco 2</a>,</strong> e in <strong>videoconferenza Big Blue Button</strong>.</p>
<p style=\"text-align: left;\">Parleremo brevemente di <strong>XMPP</strong> e delle sue caratteristiche, e del perché ci sembri migliore delle alternative. Ci concentreremo sulla filosofia del <strong>progetto Snikket</strong> e delle sue peculiarità lato client e server. Mostreremo com’è semplice installare il server, e i relativi requisiti tecnici.<br />
Quindi inviteremo i partecipanti ad unirsi a Snikket con il proprio telefono, e proveremo ad inviare messaggi in conversazioni singole e di gruppo, spiegando le caratteristiche di sicurezza predisposte. Alla fine mostreremo come installare il client XMPP desktop <strong>Gajim</strong> su Linux, usando flatpak, e come configurare la stessa utenza appena creata con l’app Snikket.</p>
<h3 style=\"text-align: center;\"><strong>La partecipazione è aperta a tutti – Ci sarà ampia possibilità di intervenire e di fare domande.</strong></h3>
<p>Per una buona organizzazione è richiesta l’iscrizione gratuita presso: <a href=\"https://fuss.bz.it/xmpp\" target=\"_blank\" rel=\"noopener\"><strong>https://fuss.bz.it/xmpp</strong></a></p>
<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2023/07/2023-07-20_xmpp-ita.pdf\"><strong>Scarica la locandina</strong> in italiano</a></p>
<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2023/07/2023-07-20_xmpp.pdf\"><strong>Scarica la locandina</strong> in inglese</a></p>
" nil nil "ba409c85f00d86d1e0672faa53de48bc") (3 (26589 17394 706010 603000) "https://www.linuxtrent.it/newpipe-incontro-con-stypox-8-novembre-a-rovereto/" "NewPipe =?utf-8?Q?=E2=80=93?= incontro con Stypox, 8 Novembre a Rovereto" "Roberto Resoli" "Sun, 23 Oct 2022 07:58:25 +0000" "<p><a href=\"https://video.linuxtrent.it/c/incontri/videos\" target=\"_blank\" rel=\"noopener\">Video sul canale “incontri”</a> dell’istanza PeerTube di LinuxTrent  e  <a href=\"https://www.linuxtrent.it/wp-content/uploads/2022/10/LinuxTrent_2022_NewPipe_presentation.pdf\">Presentazione PDF</a>.</p>
<p><a href=\"https://github.com/Stypox\" target=\"_blank\" rel=\"noopener\"><strong>Stypox</strong></a> è uno degli sviluppatori di <a href=\"https://newpipe.net/\" target=\"_blank\" rel=\"noopener\"><strong>NewPipe</strong></a>.</p>
<p><strong>NewPipe</strong> è un famoso client per Android per guardare YouTube, PeerTube e altri servizi. È disponibile su F-Droid, uno store di app che, come NewPipe, sono libere, open source e rispettose dell’utente (FOSS). Saranno analizzate le principali funzionalità, oltre ad anticiparne di future. Sarà presentata una visione complessiva del progetto e in particolare dello sviluppo del codice e di come opera il team NewPipe, spiegando ad esempio come funziona lo “scraping” (il processo per caricare le informazioni dei video mostrati) e perché garantisce una maggiore privacy. Saranno infine segnalati alcuni progetti derivati o inerenti.</p>
<h4><strong>8 Novembre 2022 ore 19 a Rovereto, Biblioteca Tartarotti presso il MART.</strong></h4>
<p><strong><a href=\"https://mobilizon.it/events/7dcc15c9-4acb-46f7-b350-82326041377c\" target=\"_blank\" rel=\"noopener\">Iscriviti su Mobilizon</a></strong> (E’ richiesta la sola email, che <strong>non</strong> sarà visibile agli organizzatori)</p>
<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2022/10/NewPipe.pdf\"><strong>Locandina</strong></a></p>
" nil nil "3daa360c324fd41ff92d3cf11dc902f5") (2 (26589 17394 705044 359000) "https://www.linuxtrent.it/linuxday-2022-ce-sempre-unalternativa/" "LinuxDay 2022: =?utf-8?B?Y+KAmcOo?= sempre =?utf-8?Q?un=E2=80=99alternativa!?=" "Roberto Resoli" "Wed, 12 Oct 2022 16:41:09 +0000" "<h4 style=\"text-align: left;\"><strong>La tecnologia permea sempre di più le nostre vite e la società</strong>, a volte con <strong>effetti positivi</strong>, altre <strong>manipolandoci e sottraendoci tempo e attenzione</strong>.</h4>
<h4 style=\"text-align: center;\"><strong>Esiste ancora possibilità di scelta?</strong></h4>
<h4 style=\"text-align: left;\">Oppure dobbiamo <strong>rassegnarci ad essere usati</strong> dalle soluzioni e sistemi che ci vengono proposti?</h4>
<h3 style=\"text-align: center;\">Se vuoi,<strong> Sabato 22 Ottobre 2022 </strong>ne parliamo <strong>ad Arco</strong>, al <strong><a href=\"https://www.linuxday.it\" target=\"_blank\" rel=\"noopener\"><strong>LinuxDay</strong></a></strong></h3>
<p style=\"text-align: left;\">… l’evento che ogni anno in decine di luoghi in tutta Italia promuove <strong>libertà e consapevolezza</strong> nella sfera digitale.</p>
<p><strong>LinuxTrent</strong> organizza, <strong>a partire dalle 8:45</strong>, un incontro in collaborazione con l’istituto scolastico <strong><a href=\"https://www.cfpupt.it/sede-di-arco\" target=\"_blank\" rel=\"noopener noreferrer\">UPT di Arco</a></strong>; durante il corso della mattinata ragioneremo insieme sulla <strong>vera essenza del cosiddetto “cloud”</strong>, parleremo di <a href=\"https://monitora-pa.it/\" target=\"_blank\" rel=\"noopener\"><strong>Monitora PA</strong></a>, <strong>l’iniziativa dirompente</strong> che “<em>un gruppo di attivisti sostenitori del diritto alla riservatezza”</em> stanno portando avanti in questi ultimi mesi, e conosceremo <a href=\"https://framatube.org/w/9dRFC6Ya11NCVeYKn8ZhiD?subtitle=it\" target=\"_blank\" rel=\"noopener\"><strong>alternative per la comunicazione sociale</strong></a> e la <a href=\"https://snikket.org\" target=\"_blank\" rel=\"noopener\"><strong>messaggistica</strong></a> concrete e rispettose delle persone e della comunità.</p>
<h1 style=\"text-align: center;\"><a href=\"/linux-day-2022-programma-e-logistica\" target=\"_blank\" rel=\"noopener noreferrer\"><strong>Programma</strong>, <strong>mappa</strong> per raggiungere il luogo della manifestazione e <strong>dettagli aggiornati</strong></a></h1>
<h1>I video della mattinata sono sul <a href=\"https://video.linuxtrent.it/c/linuxday22/videos\" target=\"_blank\" rel=\"noopener\">canale Peertube dedicato</a>!</h1>
<h3 style=\"text-align: center;\">L’incontro è assolutamente <strong>libero</strong>, <strong>rivolto</strong> ed <strong>accessibile a tutti</strong>!<br />
Ci sarà ampio spazio per chiedere, nonché condividere i propri pensieri ed esperienze.</h3>
<p><strong>Ti ringraziamo se <a href=\"https://mobilizon.it/events/b85b4f1c-e083-4aa4-b44f-c69c3d339dea\" target=\"_blank\" rel=\"noopener\">segnali la tua partecipazione su Mobilizon</a></strong> (il tuo indirizzo email sarà usato per chiederti conferma, ma non verrà registrato, e non sarà visibile agli organizzatori)</p>
" nil nil "6f90b9369b31912b14517914a2afba62") (1 (26589 17394 703781 43000) "https://www.linuxtrent.it/presentazione-del-progetto-mozilla-common-voice/" "Presentazione del progetto =?utf-8?Q?=E2=80=9CMozilla?= Common =?utf-8?Q?Voice=E2=80=9D?=" "Daniele Piccoli" "Sat, 11 Dec 2021 22:47:32 +0000" "<h3>“Mozilla Common Voice è un’iniziativa per insegnare alle macchine come parlano le persone nella vita reale.<img decoding=\"async\" class=\"alignnone size-medium\" src=\"https://www.mozillaitalia.org/img/new-logo/tricolore/icona%20tricolore%20scura.svg\" width=\"0\" height=\"0\" /></h3>
<p>La voce è naturale, la voce è umanità. Per questo l’idea di creare una tecnologia vocale utilizzabile dalle nostre macchine ci affascina così tanto. Per creare sistemi basati sulla tecnologia vocale, però, è necessaria un’altissima quantità di campioni.</p>
<p>Buona parte dei dati usati dalle grandi aziende non è accessibile alla maggioranza delle persone. Secondo noi questo soffoca l’innovazione. Per questa ragione abbiamo sviluppato Common Voice, un progetto di riconoscimento vocale aperto a tutti.” [Fonte: <a href=\"https://commonvoice.mozilla.org/it\" target=\"_blank\" rel=\"noopener\">https://commonvoice.mozilla.org/it</a>]</p>
<p>Se vi interessa scoprire più nello specifico il funzionamento di questa tecnologia e come poter contribuire, venite a trovarci <strong>mercoledì 15 dicembre 2021</strong>, presso la <a href=\"https://www.openstreetmap.org/relation/1919517\" target=\"_blank\" rel=\"noopener\">biblioteca di Rovereto – sala multimediale</a>, con inizio <strong>alle ore 18.00</strong></p>
<h1><a href=\"https://www.linuxtrent.it/wp-content/uploads/2021/12/Talk-Trento-LinuxTrent-Rid.pdf\">Scarica le presentazione</a></h1>
<h2><a href=\"https://video.linuxtrent.it/videos/watch/572b6a98-8e5d-4544-b103-0689bd8cc65b\" target=\"_blank\" rel=\"noopener\">Segui la diretta live</a></h2>
<p>Per accedere è necessario essere muniti di Green Pass</p>
<p><a href=\"https://www.linuxtrent.it/wp-content/uploads/2021/12/ProgettoCVP.pdf\">Qui trovate la locandina dell’evento</a></p>
" nil nil "ee1f3137b5d7a4473cfc6c7089cf2839")))